// Auto-generated by buffela-js, DO NOT MODIFY
import type { Serializable as _Serializable, Serializer as _Serializer } from "@buffela/serializer"
import type { Deserializable as _Deserializable, Deserializer as _Deserializer } from "@buffela/deserializer"
import type Date from "./primitives/Date"

declare const id: unique symbol

type Gender_Schema = {
    readonly FEMALE: { [id]: "Gender.FEMALE" }
    readonly MALE: { [id]: "Gender.MALE" }
}

type User_Schema = {
    readonly Anonymous: { [id]: "User.Anonymous" }

    readonly Registered: {
        readonly Viewer: { [id]: "User.Registered.Viewer" }
        readonly Organizer: { [id]: "User.Registered.Organizer" }
    }
}

type AuthTokenPayload_Schema = {}

type AuthTokenSignature_Schema = {}

export type Gender = Gender_Schema[keyof Gender_Schema]

export type User = {
    userId: string,
} & (
    {
        User_type: User_Schema["Anonymous"],
    } | {
        User_type: User_Schema["Registered"],
        vector: Uint8ClampedArray,
    } & (
        {
            Registered_type: User_Schema["Registered"]["Viewer"],
            birthDate: Date,
            countryCode: number,
            phone: string,
            gender: Gender,
        } | {
            Registered_type: User_Schema["Registered"]["Organizer"],
            email: string,
            userId: string,
        }
    )
)

export type AuthTokenPayload = {
    issuedAt: number,
    user: User,
}

export type AuthTokenSignature = {
    sha256: Buffer,
}

type _Type<T> = Partial<_Serializable<T> & _Deserializable<T>>
type _Primitive<T> = Partial<_Serializer<T> & _Deserializer<T>>

type _Schema = {
    readonly Gender: Gender_Schema & _Type<Gender>
    readonly User: User_Schema & _Type<User>
    readonly AuthTokenPayload: AuthTokenPayload_Schema & _Type<AuthTokenPayload>
    readonly AuthTokenSignature: AuthTokenSignature_Schema & _Type<AuthTokenSignature>

    primitiveTypes: {
        Date?: _Primitive<Date>
    }
}

export default _Schema
