// Auto-generated by buffela-js, DO NOT MODIFY

import type { 
    RelativeSchemaNode as _RelativeSchemaNode, 
    AbsoluteEnumEntry as _AbsoluteEnumEntry,
    AbsoluteSubtypeSchema as _AbsoluteSubtypeSchema,
} from "@buffela/parser"
import type { 
    Serializable as _Serializable, 
    Serializer as _Serializer 
} from "@buffela/serializer"
import type { 
    Deserializable as _Deserializable, 
    Deserializer as _Deserializer 
} from "@buffela/deserializer"
import type Date from "./primitives/Date.ts"

type _TypeSchema<T> = Partial<_Serializable<T> & _Deserializable<T>>
type _Primitive<T> = Partial<_Serializer<T> & _Deserializer<T>>

export type Gender = _RelativeSchemaNode<0, "Gender">

export type Phone = {
    countryCode: number,
    number: string,
}

export type User = {
    _type: _RelativeSchemaNode<0, "User">,
    userId: string,
} & (
    {
        _type: _RelativeSchemaNode<1, "Anonymous">,
    } | {
        _type: _RelativeSchemaNode<1, "Registered">,
        verified: boolean,
    } & (
        {
            _type: _RelativeSchemaNode<2, "Viewer">,
            birthDate: Date,
            gender: Gender,
            phone: (Phone | null),
        } | {
            _type: _RelativeSchemaNode<2, "Organizer">,
            roles: string[],
            userId: string,
            email: string,
        }
    )
)

export type AuthTokenPayload = {
    issuedAt: number,
    user: User,
}

export type AuthTokenSignature = {
    hmac256: Uint8Array,
}

type _Schema = {
    readonly Gender: _TypeSchema<Gender> & {
        readonly FEMALE: _AbsoluteEnumEntry<["Gender", "FEMALE"]>
        readonly MALE: _AbsoluteEnumEntry<["Gender", "MALE"]>
    }

    readonly Phone: _TypeSchema<Phone> & {}

    readonly User: _TypeSchema<User> & {
        readonly Anonymous: _AbsoluteSubtypeSchema<["User", "Anonymous"]> & {}

        readonly Registered: _AbsoluteSubtypeSchema<["User", "Registered"]> & {
            readonly Viewer: _AbsoluteSubtypeSchema<["User", "Registered", "Viewer"]> & {}

            readonly Organizer: _AbsoluteSubtypeSchema<["User", "Registered", "Organizer"]> & {}
        }
    }

    readonly AuthTokenPayload: _TypeSchema<AuthTokenPayload> & {}

    readonly AuthTokenSignature: _TypeSchema<AuthTokenSignature> & {}

    primitiveTypes: {
        Date?: _Primitive<Date>
    }
}

export default _Schema
