// Auto-generated by buffela-js, DO NOT MODIFY

import type { SchemaTypes as _Buffela } from "@buffela/parser"
import type { Serializable as _Serializable, Serializer as _Serializer } from "@buffela/serializer"
import type { Deserializable as _Deserializable, Deserializer as _Deserializer } from "@buffela/deserializer"

namespace _Primitives {
    export interface Date {
        year: number;
        month: number;
        day: number;
    }
}

export type Gender = _Buffela.AbsoluteSchemaNode<["Gender"]>

export type Phone = {
    countryCode: number,
    number: string,
}

export type User = {
    _type: _Buffela.RelativeSchemaNode<0, "User">,
    userId: string,
} & (
    {
        _type: _Buffela.RelativeSchemaNode<1, "Anonymous">,
    } | {
        _type: _Buffela.RelativeSchemaNode<1, "Registered">,
        verified: boolean,
    } & (
        {
            _type: _Buffela.RelativeSchemaNode<2, "Viewer">,
            birthDate: _Primitives.Date,
            gender: Gender,
            phone: (Phone | null),
        } | {
            _type: _Buffela.RelativeSchemaNode<2, "Organizer">,
            roles: string[],
            userId: string,
            email: string,
        }
    )
)

export type AuthTokenPayload = {
    issuedAt: number,
    user: User,
}

export type AuthTokenSignature = {
    hmac256: Uint8Array,
}

type _TypeSchema<T> = Partial<_Serializable<T> & _Deserializable<T>>
type _Primitive<T, A> = Partial<_Serializer<T, A> & _Deserializer<T, A>>

type _Schema = {
    readonly Gender: _TypeSchema<Gender> & _Buffela.EnumType<["Gender"]> & {
        readonly FEMALE: _Buffela.EnumEntry<["Gender", "FEMALE"]>
        readonly MALE: _Buffela.EnumEntry<["Gender", "MALE"]>
    }
    readonly Phone: _TypeSchema<Phone> & {}
    readonly User: _TypeSchema<User> & _Buffela.PolymorphicObjectType<["User"]> & {
        readonly Anonymous: _Buffela.PolymorphicObjectType<["User", "Anonymous"]> & {}
        readonly Registered: _Buffela.PolymorphicObjectType<["User", "Registered"]> & {
            readonly Viewer: _Buffela.PolymorphicObjectType<["User", "Registered", "Viewer"]> & {}
            readonly Organizer: _Buffela.PolymorphicObjectType<["User", "Registered", "Organizer"]> & {}
        }
    }
    readonly AuthTokenPayload: _TypeSchema<AuthTokenPayload> & {}
    readonly AuthTokenSignature: _TypeSchema<AuthTokenSignature> & {}
    primitiveTypes: {
        Date?: _Primitive<_Primitives.Date, undefined>
    }
}

export default _Schema
