// Auto-generated by buffela-js, DO NOT MODIFY
import type { Serializable as _Serializable, Serializer as _Serializer } from "@buffela/serializer"
import type { Deserializable as _Deserializable, Deserializer as _Deserializer } from "@buffela/deserializer"
import type Date from "./primitives/Date.ts"

type _NodePath<P extends object> = {
    path: { [K in keyof P]: { name: P[K] } }
}

type _RelativePath<D extends number, N extends string> = _NodePath<{ [K in D]: N }>
type _AbsolutePath<P extends string[]> = _NodePath<Omit<P, keyof any[]>>

type _SubtypeSchema<P extends string[]> = _AbsolutePath<P> & {
    instanceOf(value: unknown): value is { _type: _AbsolutePath<P> }
}

type _TypeSchema<T> = Partial<_Serializable<T> & _Deserializable<T>>
type _Primitive<T> = Partial<_Serializer<T> & _Deserializer<T>>

export type Gender = _RelativePath<0, "Gender">

export type Phone = {
    countryCode: number,
    number: string,
}

export type User = {
    _type: _RelativePath<0, "User">,
    userId: string,
} & (
    {
        _type: _RelativePath<1, "Anonymous">,
    } | {
        _type: _RelativePath<1, "Registered">,
        verified: boolean,
    } & (
        {
            _type: _RelativePath<2, "Viewer">,
            birthDate: Date,
            gender: Gender,
            phone: (Phone | null),
        } | {
            _type: _RelativePath<2, "Organizer">,
            roles: string[],
            userId: string,
            email: string,
        }
    )
)

export type AuthTokenPayload = {
    issuedAt: number,
    user: User,
}

export type AuthTokenSignature = {
    hmac256: Uint8Array,
}

type _Schema = {
    readonly Gender: _TypeSchema<Gender> & {
        readonly FEMALE: _AbsolutePath<["Gender", "FEMALE"]>
        readonly MALE: _AbsolutePath<["Gender", "MALE"]>
    }

    readonly Phone: _TypeSchema<Phone> & {}

    readonly User: _TypeSchema<User> & {
        readonly Anonymous: _SubtypeSchema<["User", "Anonymous"]> & {}

        readonly Registered: _SubtypeSchema<["User", "Registered"]> & {
            readonly Viewer: _SubtypeSchema<["User", "Registered", "Viewer"]> & {}

            readonly Organizer: _SubtypeSchema<["User", "Registered", "Organizer"]> & {}
        }
    }

    readonly AuthTokenPayload: _TypeSchema<AuthTokenPayload> & {}

    readonly AuthTokenSignature: _TypeSchema<AuthTokenSignature> & {}

    primitiveTypes: {
        Date?: _Primitive<Date>
    }
}

export default _Schema
