// Auto-generated by buffela-kotlin, DO NOT MODIFY
import type { Serializable as serializable, Serializer as serializer } from "@buffela/serializer"
import type { Deserializable as deserializable, Deserializer as deserializer } from "@buffela/deserializer"
import type Date from "./primitives/Date"

declare const id: unique symbol

type Gender_Schema = {
    readonly FEMALE: { [id]: "Gender.FEMALE" }
    readonly MALE: { [id]: "Gender.MALE" }
}

type User_Schema = {
    readonly Anonymous: { [id]: "User.Anonymous" }
    readonly Registered: { [id]: "User.Registered" }
}

type AuthTokenPayload_Schema = {}

type AuthTokenSignature_Schema = {}

type AuthToken_Schema = {}

export type Gender = Gender_Schema[keyof Gender_Schema]

export type User = {
    userId: string,
    gender: Gender,
} & (
    {
        User_type: User_Schema["Anonymous"],
    } | {
        User_type: User_Schema["Registered"],
        phone: string,
    }
)

export type AuthTokenPayload = {
    issuedAt: Date,
    user: User,
}

export type AuthTokenSignature = {
    sha256: Buffer,
}

export type AuthToken = {
    payload: AuthTokenPayload,
    signature: AuthTokenSignature,
}

type type<T> = Partial<serializable<T> & deserializable<T>>
type primitive<T> = Partial<serializer<T> & deserializer<T>>

type schema = {
    readonly Gender: Gender_Schema & type<Gender>
    readonly User: User_Schema & type<User>
    readonly AuthTokenPayload: AuthTokenPayload_Schema & type<AuthTokenPayload>
    readonly AuthTokenSignature: AuthTokenSignature_Schema & type<AuthTokenSignature>
    readonly AuthToken: AuthToken_Schema & type<AuthToken>

    primitives: {
        Date?: primitive<Date>
    }
}

export default schema
