// Auto-generated by buffela-to-types, DO NOT MODIFY

import type { Calf as calf } from "@buffela/parser/types/Calf"
type ValueOf<T extends object> = T[keyof T]

type schema = {
    readonly Gender : {
        readonly FEMALE: unique symbol
        readonly MALE: unique symbol
    }

    readonly User : calf<User> & {
        readonly RegisteredWithPhone: unique symbol
        readonly RegisteredWithEmail: unique symbol
    }

    readonly AuthToken : calf<AuthToken> & {}
}

export default schema

export type Gender = ValueOf<schema["Gender"]>

export type User = {
    userId: string,
    gender: Gender,
    hobbies: string[],
} & (
    {
        registeredWith: schema["User"]["RegisteredWithPhone"],
        countryCode: number,
        phone: string,
    } | {
        registeredWith: schema["User"]["RegisteredWithEmail"],
        email: string,
    }
)

export type AuthToken = {
    issuedAt: number,
    signature: Buffer,
    user: User,
    version?: never,
}
