// Auto-generated by buffela-to-types, DO NOT MODIFY
import type _schema from "@buffela/parser/types/Schema"
import type _primitive from "@buffela/parser/types/Primitive"

interface _Gender {
    readonly FEMALE: unique symbol
    readonly MALE: unique symbol
}

interface _User {
    readonly RegisteredWithPhone: {
        readonly Empty: unique symbol
        readonly Landline: unique symbol
        readonly Mobile: unique symbol
    }
    readonly RegisteredWithEmail: unique symbol
}

interface _AuthTokenPayload {}

interface _AuthToken {}

export type Gender = _Gender[keyof _Gender]

export type User = {
    userId: string,
    gender: Gender,
    hobbies: string,
} & (
    {
        _type: _User["RegisteredWithPhone"],
        countryCode: number,
    } & (
        {
            _type: _User["RegisteredWithPhone"]["Empty"],
        } | {
            _type: _User["RegisteredWithPhone"]["Landline"],
            phone: string,
        } | {
            _type: _User["RegisteredWithPhone"]["Mobile"],
            phone: string,
        }
    ) | {
        _type: _User["RegisteredWithEmail"],
        email: string,
    }
)

export type AuthTokenPayload = {
    issuedAt: number,
    user: User,
}

export type AuthToken = {
    payload: AuthTokenPayload,
    signature: Buffer,
}

type schema = _schema & {
    readonly Gender: _primitive<Gender> & _Gender
    readonly User: _primitive<User> & _User
    readonly AuthTokenPayload: _primitive<AuthTokenPayload> & _AuthTokenPayload
    readonly AuthToken: _primitive<AuthToken> & _AuthToken
}

export default schema
