// Auto-generated by buffela-to-types, DO NOT MODIFY
import type { Serializable as serializable, Serializer as serializer } from "@buffela/serializer"
import type { Deserializable as deserializable, Deserializer as deserializer } from "@buffela/deserializer"
import type Date from "./primitives/Date"

declare const id: unique symbol

type type<T> = Partial<serializable<T> & deserializable<T>>
type primitive<T> = Partial<serializer<T> & deserializer<T>>

type _Gender = {
    readonly FEMALE: { [id]: "Gender.FEMALE" }
    readonly MALE: { [id]: "Gender.MALE" }
}

type _User = {
    readonly Anonymous: { [id]: "User.Anonymous" }
    readonly Registered: { [id]: "User.Registered" }
}

type _AuthTokenPayload = {}

type _AuthTokenSignature = {}

type _AuthToken = {}

export type Gender = _Gender[keyof _Gender]

export type User = {
    userId: string,
    gender: Gender,
} & (
    {
        User_type: _User["Anonymous"],
    } | {
        User_type: _User["Registered"],
        phone: string,
    }
)

export type AuthTokenPayload = {
    issuedAt: Date,
    user: User,
}

export type AuthTokenSignature = {
    sha256: Buffer,
}

export type AuthToken = {
    payload: AuthTokenPayload,
    signature: AuthTokenSignature,
}

type schema = {
    readonly Gender: _Gender & type<Gender>
    readonly User: _User & type<User>
    readonly AuthTokenPayload: _AuthTokenPayload & type<AuthTokenPayload>
    readonly AuthTokenSignature: _AuthTokenSignature & type<AuthTokenSignature>
    readonly AuthToken: _AuthToken & type<AuthToken>

    primitives: {
        Date?: primitive<Date>
    }
}

export default schema
