// Auto-generated by buffela-kotlin, DO NOT MODIFY
import type { Serializable as _Serializable, Serializer as _Serializer } from "@buffela/serializer"
import type { Deserializable as _Deserializable, Deserializer as _Deserializer } from "@buffela/deserializer"
import type Date from "./primitives/Date"

declare const id: unique symbol

type Gender_Schema = {
    readonly FEMALE: { [id]: "Gender.FEMALE" }
    readonly MALE: { [id]: "Gender.MALE" }
}

type User_Schema = {
    readonly Anonymous: { [id]: "User.Anonymous" }
    readonly Registered: { [id]: "User.Registered" }
}

type AuthTokenPayload_Schema = {}

type AuthTokenSignature_Schema = {}

type AuthToken_Schema = {}

export type Gender = Gender_Schema[keyof Gender_Schema]

export type User = {
    userId: string,
    gender: Gender,
} & (
    {
        User_type: User_Schema["Anonymous"],
    } | {
        User_type: User_Schema["Registered"],
        phone: string,
    }
)

export type AuthTokenPayload = {
    issuedAt: Date,
    user: User,
}

export type AuthTokenSignature = {
    sha256: Buffer,
}

export type AuthToken = {
    payload: AuthTokenPayload,
    signature: AuthTokenSignature,
}

type _Type<T> = Partial<_Serializable<T> & _Deserializable<T>>
type _Primitive<T> = Partial<_Serializer<T> & _Deserializer<T>>

type _Schema = {
    readonly Gender: Gender_Schema & _Type<Gender>
    readonly User: User_Schema & _Type<User>
    readonly AuthTokenPayload: AuthTokenPayload_Schema & _Type<AuthTokenPayload>
    readonly AuthTokenSignature: AuthTokenSignature_Schema & _Type<AuthTokenSignature>
    readonly AuthToken: AuthToken_Schema & _Type<AuthToken>

    primitives: {
        Date?: _Primitive<Date>
    }
}

export default _Schema
