// Auto-generated by buffela-to-types, DO NOT MODIFY
import type { Serializable as serializable, Serializer as serializer } from "@buffela/serializer"
import type { Deserializable as deserializable, Deserializer as deserializer } from "@buffela/deserializer"
import type Date from "./primitives/Date"

declare const id: unique symbol

type type<T> = Partial<serializable<T> & deserializable<T>>
type primitive<T> = Partial<serializer<T> & deserializer<T>>

type _Gender = {
    readonly FEMALE: { [id]: "Gender.FEMALE" }
    readonly MALE: { [id]: "Gender.MALE" }
}

type _User = {
    readonly RegisteredWithPhone: {
        readonly Empty: { [id]: "User.RegisteredWithPhone.Empty" }
        readonly Landline: { [id]: "User.RegisteredWithPhone.Landline" }
        readonly Mobile: { [id]: "User.RegisteredWithPhone.Mobile" }
    }
    readonly RegisteredWithEmail: { [id]: "User.RegisteredWithEmail" }
}

type _AuthTokenPayload = {}

type _AuthToken = {}

export type Gender = _Gender[keyof _Gender]

export type User = {
    userId: string,
    gender: Gender,
    hobbies: string,
    registrationDate: Date,
} & (
    {
        _type: _User["RegisteredWithPhone"],
        countryCode: number,
    } & (
        {
            _type: _User["RegisteredWithPhone"]["Empty"],
        } | {
            _type: _User["RegisteredWithPhone"]["Landline"],
            phone: string,
        } | {
            _type: _User["RegisteredWithPhone"]["Mobile"],
            phone: string,
        }
    ) | {
        _type: _User["RegisteredWithEmail"],
        email: string,
    }
)

export type AuthTokenPayload = {
    issuedAt: number,
    user: User,
}

export type AuthToken = {
    payload: AuthTokenPayload,
    signature: Buffer,
}

type schema = {
    readonly Gender: _Gender & type<Gender>
    readonly User: _User & type<User>
    readonly AuthTokenPayload: _AuthTokenPayload & type<AuthTokenPayload>
    readonly AuthToken: _AuthToken & type<AuthToken>

    primitives: {
        Date?: primitive<Date>
    }
}

export default schema
