#!/usr/bin/env node

const process = require("node:process");

const yargs = require('yargs')
const {hideBin} = require("yargs/helpers");

const { parseBuffelaSchema, buffelaSchema } = require("@buffela/parser")
const { readBuffelaFile, Printer, fileUtils } = require("@buffela/tools-common");

const {printEnumCalfClass} = require("./utils/enumTypeUtils");
const {printDataCalfClass} = require("./utils/dataTypeUtils");
const {printSerializerImports} = require("./utils/fieldSerializationUtils");
const {printDeserializerImports} = require("./utils/fieldDeserializationUtils");

yargs()
    .command({
        command: 'types <schema> [destination]',
        describe: 'Generate kotlin types for a buffela schema',
        builder: (yargs) => yargs
            .positional('schema', {
                describe: 'Schema path',
                type: 'string'
            })
            .positional('destination', {
                describe: 'Output file or directory',
                type: 'string',
                default: '.',
                defaultDescription: '(Current directory)'
            })
            .option('package', {
                alias: 'p',
                describe: 'The package name for the generated code',
                type: 'string',
                default: ''
            })
            .option('serializer', {
                describe: 'Generate serializer code',
                type: 'boolean',
                default: true
            })
            .option('deserializer', {
                describe: 'Generate deserializer code',
                type: 'boolean',
                default: true
            }),
        handler: (argv) => {
            const inputFile = readBuffelaFile(argv.schema)
            const buffela = parseBuffelaSchema(inputFile.schema)

            const outputStream = fileUtils.getFileOutputStream(argv.destination, inputFile.name + ".kt")
            global.printer = new Printer(outputStream)
            global.options = { serializerEnabled: argv.serializer, deserializerEnabled: argv.deserializer }

            printer.line("// Auto-generated by buffela-kotlin, DO NOT MODIFY")

            if (argv.package)
                printer.line(`package ${argv.package}`)

            if (options.serializerEnabled)
                printSerializerImports()

            if (options.deserializerEnabled)
                printDeserializerImports()

            for (const calfName in buffela) {
                const calf = buffela[calfName]

                if (calf.type === "enum") {
                    printEnumCalfClass(calf)
                } else if (calf.type === "data") {
                    printDataCalfClass(calf)
                } else {
                    throw new Error(`Unknown definition type '${calf.type}' at '${calf.name}'`)
                }
            }

            outputStream.end()
        }
    })
    .command({
        command: 'schema [destination]',
        describe: 'Print the buffela JSON schema',
        builder: (yargs) => yargs.positional('destination', {
            describe: 'The output file or directory',
            type: 'string',
            default: '.',
            defaultDescription: '(Current directory)'
        }),
        handler: (argv) => {
            const outputStream = fileUtils.getFileOutputStream(argv.destination, "buffela-schema.json")
            outputStream.write(JSON.stringify(buffelaSchema, null, 2))
            outputStream.end()
        }
    })
    .demandCommand(1)
    .help()
    .parse(hideBin(process.argv))