const { printSchemaTypes } = require("./schemaTypeUtils");
const { printSchema } = require("./schemaUtils");

function printImports() {
    printer.line(`import type { 
    RelativeSchemaNode as _RelativeSchemaNode, 
    AbsoluteEnumEntry as _AbsoluteEnumEntry,
    AbsoluteSubtypeSchema as _AbsoluteSubtypeSchema,
} from "@buffela/parser"`)

    if (options.serializerEnabled) printer.line(`import type { 
    Serializable as _Serializable, 
    Serializer as _Serializer 
} from "@buffela/serializer"`)

    if (options.deserializerEnabled) printer.line(`import type { 
    Deserializable as _Deserializable, 
    Deserializer as _Deserializer 
} from "@buffela/deserializer"`)

    printer.line()
    printer.line(options.primitives)
}

function combineExtensions(extensions) {
    if (!extensions.length) return '{}'
    return extensions.join(' & ')
}

function printUtils() {
    const typeExtensions = [], primitiveExtensions = []

    if (options.serializerEnabled) {
        typeExtensions.push('_Serializable<T>')
        primitiveExtensions.push('_Serializer<T>')
    }

    if (options.deserializerEnabled) {
        typeExtensions.push('_Deserializable<T>')
        primitiveExtensions.push('_Deserializer<T>')
    }

    printer.line(`type _TypeSchema<T> = Partial<${combineExtensions(typeExtensions)}>`)
    printer.line(`type _Primitive<T> = Partial<${combineExtensions(primitiveExtensions)}>`)
}

function printTypes() {
    printer.line("// Auto-generated by buffela-js, DO NOT MODIFY\n")

    printImports()
    printUtils()
    printSchemaTypes()
    printSchema()
}

module.exports = { printTypes }