const nativeTypes = require("../constants/nativeTypes");
const {printTypeSchemata} = require("./typeSchemaUtils");
const {printSchemaTypes} = require("./schemaTypeUtils");
const {printSchema} = require("./schemaUtils");

function printImports() {
    if (options.serializerEnabled)
        printer.line('import type { Serializable as serializable, Serializer as serializer } from "@buffela/serializer"')

    if (options.deserializerEnabled)
        printer.line('import type { Deserializable as deserializable, Deserializer as deserializer } from "@buffela/deserializer"')

    for (const type in schema.primitives) {
        if (type in nativeTypes) continue;
        printer.line(`import type ${type} from "./primitives/${type}"`)
    }
}

function printTypes() {
    printer.line("// Auto-generated by buffela-kotlin, DO NOT MODIFY")

    printImports()
    printTypeSchemata()
    printSchemaTypes()
    printSchema()
}

module.exports = { printTypes }