#!/usr/bin/env node

const process = require("node:process");
const path = require("node:path");
const fs = require("node:fs")

const yargs = require('yargs');
const { hideBin } = require("yargs/helpers");
const { parseSchema } = require("@buffela/parser");
const {
    readSchemaFileSync,
    processFiles,
    tryReadFileSync,
    Printer
} = require('@buffela/tools-common')

const {
    printComplexTypeImports,
    printComplexTypes
} = require("./utils/complexTypeUtils");

const {
    printSchemaType,
    printSchemaTypeImports
} = require("./utils/schemaUtils");

yargs()
    .command({
        command: '* <schemaFile> [outputDir]',
        describe: 'Converts buffela schemata to JSON and generates type definitions',
        builder: (yargs) => yargs
            .option('rootDirs', {
                alias: 'r',
                describe: 'The directory paths that are in scope',
                type: 'array',
                default: ['.'],
                defaultDescription: '(The current working directory)'
            })
            .positional('schemaFile', {
                describe: 'Schema path, relative to each root directory',
                type: 'string'
            })
            .positional('outputDir', {
                describe: 'Output directory path, relative to each root directory',
                type: 'string',
                default: '.',
                defaultDescription: '(The root directory)'
            })
            .option('jsonDir', {
                alias: 'j',
                describe: 'Json output directory path, relative to the output directory',
                type: 'string',
                default: '.',
                defaultDescription: '(The output directory)'
            })
            .option('typeDefDir', {
                alias: 't',
                describe: 'Type definition output directory path, relative to the output directory',
                type: 'string',
                default: '.',
                defaultDescription: '(The output directory)'
            })
            .option('watch', {
                alias: 'w',
                describe: 'Watch for changes',
                type: 'boolean',
                default: false
            })
            .option('serializer', {
                describe: 'Generate serializer types',
                type: 'boolean',
                default: true
            })
            .option('deserializer', {
                describe: 'Generate deserializer types',
                type: 'boolean',
                default: true
            }),
        handler: (argv) => {
            processFiles(argv.rootDirs, argv.schemaFile, argv.watch, (paths) => {
                console.log("Compiling", paths.inputFile)

                const schemaFile = readSchemaFileSync(paths.inputFile)
                if (schemaFile == null) return

                const outputDirPath = path.join(paths.outputRootDir, argv.outputDir)

                if (argv.jsonDir) {
                    const jsonOutputDirPath = path.join(outputDirPath, argv.jsonDir, paths.outputSubDir)
                    fs.mkdirSync(jsonOutputDirPath, { recursive: true })

                    const jsonOutputFilePath = path.join(jsonOutputDirPath, schemaFile.name + ".json")
                    const jsonOutputFileStream = fs.createWriteStream(jsonOutputFilePath)

                    jsonOutputFileStream.write(JSON.stringify(schemaFile.schema))
                    jsonOutputFileStream.end()
                }

                if (argv.typeDefDir) {
                    const typeDefOutputDirPath = path.join(outputDirPath, argv.typeDefDir, paths.outputSubDir)
                    fs.mkdirSync(typeDefOutputDirPath, { recursive: true })

                    const primitivesFilePath = path.join(typeDefOutputDirPath, schemaFile.name + ".primitives.ts")
                    const primitivesFileContents = tryReadFileSync(primitivesFilePath)

                    const typeDefOutputFilePath = path.join(typeDefOutputDirPath, schemaFile.name + ".ts")
                    const typeDefOutputFileStream = fs.createWriteStream(typeDefOutputFilePath)

                    global.schema = parseSchema(schemaFile.schema)
                    global.printer = new Printer(typeDefOutputFileStream)
                    global.options = {
                        serializerEnabled: argv.serializer,
                        deserializerEnabled: argv.deserializer,
                        primitives: primitivesFileContents ?? ""
                    }

                    printer.line("// Auto-generated by buffela-js, DO NOT MODIFY\n")

                    printComplexTypeImports()
                    printSchemaTypeImports()

                    printComplexTypes()
                    printSchemaType()

                    typeDefOutputFileStream.end()
                }
            })
        }
    })
    .strict()
    .demandCommand(1)
    .help()
    .parse(hideBin(process.argv))