// Auto-generated by buffela-kotlin, DO NOT MODIFY
package gr.elaevents.buffela.examples.authToken
typealias _Serializable = gr.elaevents.buffela.serialization.Serializable
typealias _SerializerBuffer = gr.elaevents.buffela.serialization.SerializerBuffer
typealias _Deserializer<T> = gr.elaevents.buffela.deserialization.Deserializer<T>
typealias _DeserializerBuffer = gr.elaevents.buffela.deserialization.DeserializerBuffer

enum class Gender: _Serializable {
    FEMALE,
    MALE,
    ;

    override fun serialize(buffer: _SerializerBuffer) {
        buffer.writeUnsigned(this.ordinal.toUInt(), 1)
    }

    companion object Deserializer: _Deserializer<Gender> {
        override fun deserialize(buffer: _DeserializerBuffer): Gender {
            return Gender.entries[buffer.readUnsigned(1).toInt()]
        }
    }
}

class Phone: _Serializable {
    val countryCode: UInt
    val number: String

    constructor(
        countryCode: UInt,
        number: String,
    ): super() {
        this.countryCode = countryCode
        this.number = number
    }

    protected fun serializeLeafIndex(buffer: _SerializerBuffer, index: Int) {
        if (index != 0) {
            throw IllegalStateException("Expected length '0' (got '${index}')")
        }
    }

    override fun serialize(buffer: _SerializerBuffer) {
        this.serializeLeafIndex(buffer, 0)
        buffer.writeUnsigned(this.countryCode, 10)
        buffer.writeString(this.number, true)
    }

    internal constructor(buffer: _DeserializerBuffer) {
        this.countryCode = buffer.readUnsigned(10)
        this.number = buffer.readString()
    }

    companion object Deserializer: _Deserializer<Phone> {
        override fun deserialize(buffer: _DeserializerBuffer): Phone {
            return when(0) {
                0 -> Phone(buffer)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }
}

sealed class User: _Serializable {
    private val _userId: String
    open val userId get() = this._userId

    constructor(
        userId: String,
    ): super() {
        this._userId = userId
    }

    protected fun serializeLeafIndex(buffer: _SerializerBuffer, index: Int) {
        buffer.writeUnsigned(index.toUInt(), 2)
    }

    protected open fun userId(buffer: _SerializerBuffer) {
        if (this.userId.length != 36) {
            throw IllegalStateException("Expected length '36' (got '${this.userId.length}')")
        }
        buffer.writeString(this.userId)
    }

    override fun serialize(buffer: _SerializerBuffer) {
        this.userId(buffer)
    }
    protected open fun userId(buffer: _DeserializerBuffer) = buffer.readString(36)

    constructor(buffer: _DeserializerBuffer) {
        this._userId = this.userId(buffer)
    }

    companion object Deserializer: _Deserializer<User> {
        override fun deserialize(buffer: _DeserializerBuffer): User {
            return when(buffer.readUnsigned(2).toInt()) {
                0 -> Anonymous(buffer)
                1 -> Registered.Viewer(buffer)
                2 -> Registered.Organizer(buffer)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }

    class Anonymous: User {
        constructor(
            userId: String,
        ): super(
            userId,
        ) {}

        override fun serialize(buffer: _SerializerBuffer) {
            this.serializeLeafIndex(buffer, 0)
            super.serialize(buffer)
        }

        internal constructor(buffer: _DeserializerBuffer): super(buffer) {}
    }

    sealed class Registered: User {
        val verified: Boolean

        constructor(
            userId: String,
            verified: Boolean,
        ): super(
            userId,
        ) {
            this.verified = verified
        }

        override fun serialize(buffer: _SerializerBuffer) {
            super.serialize(buffer)
            buffer.writeBoolean(this.verified)
        }

        constructor(buffer: _DeserializerBuffer): super(buffer) {
            this.verified = buffer.readBoolean()
        }

        class Viewer: Registered {
            val birthDate: Date
            val gender: Gender
            val phone: Phone?

            constructor(
                userId: String,
                verified: Boolean,
                birthDate: Date,
                gender: Gender,
                phone: Phone?,
            ): super(
                userId,
                verified,
            ) {
                this.birthDate = birthDate
                this.gender = gender
                this.phone = phone
            }

            override fun serialize(buffer: _SerializerBuffer) {
                this.serializeLeafIndex(buffer, 1)
                super.serialize(buffer)
                buffer.writeDate(this.birthDate)
                this.gender.serialize(buffer)
                buffer.writeBoolean(this.phone != null)

                this.phone?.let {
                    this.phone.serialize(buffer)
                }
            }

            internal constructor(buffer: _DeserializerBuffer): super(buffer) {
                this.birthDate = buffer.readDate()
                this.gender = Gender.deserialize(buffer)
                this.phone = if (buffer.readBoolean()) Phone.deserialize(buffer) else null
            }
        }

        class Organizer: Registered {
            val roles: Array<String>
            override val userId get() = super.userId as String
            val email: String

            constructor(
                userId: String,
                verified: Boolean,
                roles: Array<String>,
                email: String,
            ): super(
                userId,
                verified,
            ) {
                this.roles = roles
                this.email = email
            }

            override fun userId(buffer: _SerializerBuffer) {
                buffer.writeString(this.userId, true)
            }

            override fun serialize(buffer: _SerializerBuffer) {
                this.serializeLeafIndex(buffer, 2)
                super.serialize(buffer)
                buffer.writeUByte(this.roles.size.toUByte())

                for (item1 in this.roles) {
                    buffer.writeString(item1, true)
                }
                buffer.writeString(this.email, true)
            }
            override fun userId(buffer: _DeserializerBuffer) = buffer.readString()

            internal constructor(buffer: _DeserializerBuffer): super(buffer) {
                this.roles = Array(buffer.readUByte().toInt()) { _ -> buffer.readString() }
                this.email = buffer.readString()
            }
        }
    }
}

class AuthTokenPayload: _Serializable {
    val issuedAt: Double
    val user: User

    constructor(
        issuedAt: Double,
        user: User,
    ): super() {
        this.issuedAt = issuedAt
        this.user = user
    }

    protected fun serializeLeafIndex(buffer: _SerializerBuffer, index: Int) {
        if (index != 0) {
            throw IllegalStateException("Expected length '0' (got '${index}')")
        }
    }

    override fun serialize(buffer: _SerializerBuffer) {
        this.serializeLeafIndex(buffer, 0)
        buffer.writeDouble(this.issuedAt)
        this.user.serialize(buffer)
    }

    internal constructor(buffer: _DeserializerBuffer) {
        this.issuedAt = buffer.readDouble()
        this.user = User.deserialize(buffer)
    }

    companion object Deserializer: _Deserializer<AuthTokenPayload> {
        override fun deserialize(buffer: _DeserializerBuffer): AuthTokenPayload {
            return when(0) {
                0 -> AuthTokenPayload(buffer)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }
}

class AuthTokenSignature: _Serializable {
    val hmac256: ByteArray

    constructor(
        hmac256: ByteArray,
    ): super() {
        this.hmac256 = hmac256
    }

    protected fun serializeLeafIndex(buffer: _SerializerBuffer, index: Int) {
        if (index != 0) {
            throw IllegalStateException("Expected length '0' (got '${index}')")
        }
    }

    override fun serialize(buffer: _SerializerBuffer) {
        this.serializeLeafIndex(buffer, 0)

        if (this.hmac256.size != 32) {
            throw IllegalStateException("Expected length '32' (got '${this.hmac256.size}')")
        }
        buffer.writeBytes(this.hmac256)
    }

    internal constructor(buffer: _DeserializerBuffer) {
        this.hmac256 = buffer.readBytes(32)
    }

    companion object Deserializer: _Deserializer<AuthTokenSignature> {
        override fun deserialize(buffer: _DeserializerBuffer): AuthTokenSignature {
            return when(0) {
                0 -> AuthTokenSignature(buffer)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }
}
