package gr.elaevents.buffela.examples.authToken

import gr.elaevents.buffela.deserialization.Deserializer
import gr.elaevents.buffela.deserialization.DeserializerBuffer
import gr.elaevents.buffela.serialization.Serializable
import gr.elaevents.buffela.serialization.SerializerBuffer

// Auto-generated by buffela-kotlin, DO NOT MODIFY
typealias _Serializable = Serializable
typealias _SerializerBuffer = SerializerBuffer
typealias _Deserializer<T> = Deserializer<T>
typealias _DeserializerBuffer = DeserializerBuffer

enum class Gender: _Serializable {
    FEMALE,
    MALE,
    ;

    override fun serialize(buffer: _SerializerBuffer) {
        buffer.writeUnsigned(this.ordinal.toUInt(), 2)
    }

    companion object Deserializer: _Deserializer<Gender> {
        override fun deserialize(buffer: _DeserializerBuffer): Gender {
            return entries[buffer.readUnsigned(2).toInt()]
        }
    }
}

sealed class User: _Serializable {
    private val _userId: String
    open val userId get() = this._userId

    constructor(
        userId: String,
    ): super() {
        this._userId = userId
    }

    protected fun serializeLeafIndex(buffer: _SerializerBuffer, index: Int) {
        buffer.writeUnsigned(index.toUInt(), 3)
    }

    protected open fun userId(buffer: _SerializerBuffer) {
        if (this.userId.length != 36) {
            throw IllegalStateException("Expected string length '36' (got '${this.userId.length}')")
        }
        buffer.writeString(this.userId)
    }

    override fun serialize(buffer: _SerializerBuffer) {
        this.userId(buffer)
    }
    protected open fun userId(buffer: _DeserializerBuffer) = buffer.readString(36)

    constructor(buffer: _DeserializerBuffer) {
        this._userId = this.userId(buffer)
    }

    companion object Deserializer: _Deserializer<User> {
        override fun deserialize(buffer: _DeserializerBuffer): User {
            return when(buffer.readUnsigned(3).toInt()) {
                0 -> Anonymous(buffer)
                1 -> Registered.Viewer(buffer)
                2 -> Registered.Organizer(buffer)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }

    class Anonymous: User {
        constructor(
            userId: String,
        ): super(
            userId,
        ) {}

        override fun serialize(buffer: _SerializerBuffer) {
            this.serializeLeafIndex(buffer, 0)
            super.serialize(buffer)
        }

        internal constructor(buffer: _DeserializerBuffer): super(buffer) {}
    }

    sealed class Registered: User {
        val verified: Boolean

        constructor(
            userId: String,
            verified: Boolean,
        ): super(
            userId,
        ) {
            this.verified = verified
        }

        override fun serialize(buffer: _SerializerBuffer) {
            super.serialize(buffer)
            buffer.writeBoolean(this.verified)
        }

        constructor(buffer: _DeserializerBuffer): super(buffer) {
            this.verified = buffer.readBoolean()
        }

        class Viewer: Registered {
            val birthDate: Date
            val countryCode: UInt
            val phone: String
            val gender: Gender

            constructor(
                userId: String,
                verified: Boolean,
                birthDate: Date,
                countryCode: UInt,
                phone: String,
                gender: Gender,
            ): super(
                userId,
                verified,
            ) {
                this.birthDate = birthDate
                this.countryCode = countryCode
                this.phone = phone
                this.gender = gender
            }

            override fun serialize(buffer: _SerializerBuffer) {
                this.serializeLeafIndex(buffer, 1)
                super.serialize(buffer)
                buffer.writeDate(this.birthDate)
                buffer.writeUnsigned(this.countryCode, 10)
                buffer.writeString(this.phone, true)
                this.gender.serialize(buffer)
            }

            internal constructor(buffer: _DeserializerBuffer): super(buffer) {
                this.birthDate = buffer.readDate()
                this.countryCode = buffer.readUnsigned(10)
                this.phone = buffer.readString()
                this.gender = Gender.deserialize(buffer)
            }
        }

        class Organizer: Registered {
            val email: String
            override val userId get() = super.userId as String

            constructor(
                userId: String,
                verified: Boolean,
                email: String,
            ): super(
                userId,
                verified,
            ) {
                this.email = email
            }

            override fun userId(buffer: _SerializerBuffer) {
                buffer.writeString(this.userId, true)
            }

            override fun serialize(buffer: _SerializerBuffer) {
                this.serializeLeafIndex(buffer, 2)
                super.serialize(buffer)
                buffer.writeString(this.email, true)
            }
            override fun userId(buffer: _DeserializerBuffer) = buffer.readString()

            internal constructor(buffer: _DeserializerBuffer): super(buffer) {
                this.email = buffer.readString()
            }
        }
    }
}

class AuthTokenPayload: _Serializable {
    val issuedAt: Double
    val user: User

    constructor(
        issuedAt: Double,
        user: User,
    ): super() {
        this.issuedAt = issuedAt
        this.user = user
    }

    override fun serialize(buffer: _SerializerBuffer) {
        buffer.writeDouble(this.issuedAt)
        this.user.serialize(buffer)
    }

    internal constructor(buffer: _DeserializerBuffer) {
        this.issuedAt = buffer.readDouble()
        this.user = User.deserialize(buffer)
    }

    companion object Deserializer: _Deserializer<AuthTokenPayload> {
        override fun deserialize(buffer: _DeserializerBuffer): AuthTokenPayload {
            return AuthTokenPayload(buffer)
        }
    }
}

class AuthTokenSignature: _Serializable {
    val sha256: ByteArray

    constructor(
        sha256: ByteArray,
    ): super() {
        this.sha256 = sha256
    }

    override fun serialize(buffer: _SerializerBuffer) {
        if (this.sha256.size != 32) {
            throw IllegalStateException("Expected size '32' (got '${this.sha256.size}')")
        }
        buffer.writeByteArray(this.sha256)
    }

    internal constructor(buffer: _DeserializerBuffer) {
        this.sha256 = buffer.readByteArray(32)
    }

    companion object Deserializer: _Deserializer<AuthTokenSignature> {
        override fun deserialize(buffer: _DeserializerBuffer): AuthTokenSignature {
            return AuthTokenSignature(buffer)
        }
    }
}
