// Auto-generated by buffela-to-kotlin, DO NOT MODIFY
package gr.elaevents.buffela.examples.simple

import kotlinx.io.writeDoubleLe
import kotlinx.io.writeFloatLe
import kotlinx.io.writeUByte
import kotlinx.io.writeUIntLe
import kotlinx.io.writeULongLe
import kotlinx.io.writeUShortLe
import gr.elaevents.buffela.internal.utils.writeStringNt

import kotlinx.io.readDoubleLe
import kotlinx.io.readFloatLe
import kotlinx.io.readUByte
import kotlinx.io.readUIntLe
import kotlinx.io.readULongLe
import kotlinx.io.readUShortLe
import kotlinx.io.readByteArray
import gr.elaevents.buffela.internal.utils.readStringNt

enum class Gender {
    FEMALE,
    MALE,
}

sealed class User: gr.elaevents.buffela.schema.Serializable {
    val userId: String
    val gender: Gender
    val hobbies: Array<String>

    constructor(
        userId: String,
        gender: Gender,
        hobbies: Array<String>,
    ): super() {
        this.userId = userId
        this.gender = gender
        this.hobbies = hobbies
    }

    override fun serializeHeader(packet: kotlinx.io.Sink) {
        packet.writeUByte(_leafIndex)
    }

    override fun serializeBody(packet: kotlinx.io.Sink) {
        packet.writeStringNt(this.userId)
        packet.writeUByte(this.gender.ordinal.toUByte())
        packet.writeUByte(this.hobbies.size.toUByte())

        for (item1 in this.hobbies) {
            packet.writeStringNt(item1)
        }
    }

    protected constructor(packet: kotlinx.io.Source): super() {
        this.userId = packet.readStringNt()
        this.gender = Gender.entries[packet.readUByte().toInt()]
        this.hobbies = Array(packet.readUByte().toInt()) { _ -> packet.readStringNt() }
    }

    companion object Deserializer {
        private fun validateHeader(packet: kotlinx.io.Source) {}

        fun deserialize(packet: kotlinx.io.Source): User {
            validateHeader(packet)

            return when(packet.readUByte().toInt()) {
                0 -> RegisteredWithPhone.deserialize(packet)
                1 -> RegisteredWithEmail.deserialize(packet)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }

    final class RegisteredWithPhone: User {
        val countryCode: UByte
        val phone: String

        constructor(
            userId: String,
            gender: Gender,
            hobbies: Array<String>,
            countryCode: UByte,
            phone: String,
        ): super(
            userId,
            gender,
            hobbies,
        ) {
            this.countryCode = countryCode
            this.phone = phone
        }
        override val _leafIndex: UByte = 0u

        override fun serializeHeader(packet: kotlinx.io.Sink) {
            super.serializeHeader(packet)
        }

        override fun serializeBody(packet: kotlinx.io.Sink) {
            super.serializeBody(packet)
            packet.writeUByte(this.countryCode)
            packet.writeStringNt(this.phone)
        }

        private constructor(packet: kotlinx.io.Source): super(packet) {
            this.countryCode = packet.readUByte()
            this.phone = packet.readStringNt()
        }

        internal companion object Deserializer {
            private fun validateHeader(packet: kotlinx.io.Source) {}

            fun deserialize(packet: kotlinx.io.Source): RegisteredWithPhone {
                validateHeader(packet)
                return RegisteredWithPhone(packet)
            }
        }
    }

    final class RegisteredWithEmail: User {
        val email: String

        constructor(
            userId: String,
            gender: Gender,
            hobbies: Array<String>,
            email: String,
        ): super(
            userId,
            gender,
            hobbies,
        ) {
            this.email = email
        }
        override val _leafIndex: UByte = 1u

        override fun serializeHeader(packet: kotlinx.io.Sink) {
            super.serializeHeader(packet)
        }

        override fun serializeBody(packet: kotlinx.io.Sink) {
            super.serializeBody(packet)
            packet.writeStringNt(this.email)
        }

        private constructor(packet: kotlinx.io.Source): super(packet) {
            this.email = packet.readStringNt()
        }

        internal companion object Deserializer {
            private fun validateHeader(packet: kotlinx.io.Source) {}

            fun deserialize(packet: kotlinx.io.Source): RegisteredWithEmail {
                validateHeader(packet)
                return RegisteredWithEmail(packet)
            }
        }
    }
}

final class AuthToken: gr.elaevents.buffela.schema.Serializable {
    val issuedAt: Double
    val signature: ByteArray
    val user: User

    constructor(
        issuedAt: Double,
        signature: ByteArray,
        user: User,
    ): super() {
        this.issuedAt = issuedAt
        this.signature = signature
        this.user = user
    }
    override val _leafIndex: UByte = 0u

    override fun serializeHeader(packet: kotlinx.io.Sink) {
        packet.writeUByte(1u)
    }

    override fun serializeBody(packet: kotlinx.io.Sink) {
        packet.writeDoubleLe(this.issuedAt)
        packet.write(this.signature)
        this.user.serialize(packet)
    }

    private constructor(packet: kotlinx.io.Source): super() {
        this.issuedAt = packet.readDoubleLe()
        this.signature = packet.readByteArray(32)
        this.user = User.deserialize(packet)
    }

    companion object Deserializer {
        private fun validateHeader(packet: kotlinx.io.Source) {
            if (
                packet.readUByte() != 1u.toUByte()
            ) throw IllegalStateException("Incompatible packet version")
        }

        fun deserialize(packet: kotlinx.io.Source): AuthToken {
            validateHeader(packet)
            return AuthToken(packet)
        }
    }
}
