const nativeTypes = {
    "UByte":            "UByte",
    "UShort":           "UShort",
    "Int":              "Int",
    "String":           "String",
    "Boolean":          "Boolean",
    "Byte":             "Byte",
    "Short":            "Short",
    "Long":             "Long",
    "Float":            "Float",
    "Double":           "Double",
    "UInt":             "UInt",
    "ULong":            "ULong",
    "Signed":           "Int",
    "Unsigned":         "UInt",
    "UByteArray":       "UByteArray",
    "UShortArray":      "UShortArray",
    "UIntArray":        "UIntArray",
    "ULongArray":       "ULongArray",
    "BooleanArray":     "BooleanArray",
    "ByteArray":        "ByteArray",
    "ShortArray":       "ShortArray",
    "IntArray":         "IntArray",
    "LongArray":        "LongArray",
    "FloatArray":       "FloatArray",
    "DoubleArray":      "DoubleArray",
    "Bytes":            "ByteArray",
}

module.exports = nativeTypes