const {printSerializerAliases} = require("./fieldSerializationUtils");
const {printDeserializerAliases} = require("./fieldDeserializationUtils");
const {printEnumTypeClass} = require("./enumTypeUtils");
const {printRootObjectTypeClass} = require("./objectTypeUtils");

function printTypes() {
    printer.line("// Auto-generated by buffela-kotlin, DO NOT MODIFY")

    if (options.package)
        printer.line(`package ${options.package}`)

    if (options.serializerEnabled)
        printSerializerAliases()

    if (options.deserializerEnabled)
        printDeserializerAliases()

    for (
        /** @type {import('@buffela/parser').TypeName} */
        const name in schema
    ) {
        const type = schema[name]

        if (type.kind === "enum") {
            printEnumTypeClass(type)
        } else if (type.kind === "object") {
            printRootObjectTypeClass(type)
        }
    }
}

module.exports = { printTypes }